name: MobSF

on:
  push:
    branches: [ "main", "tests","tests-lightver" ]
  pull_request:
    branches: [ "main", "tests","tests-lightver" ]
  schedule:
    - cron: '17 23 * * 2'

permissions:
  contents: read

jobs:
  mobile-security:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: 🥏 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 🔍 Run mobsfscan
        run: |
          pip install mobsfscan --quiet
          mobsfscan . --sarif --output results.sarif || true

      - name: 📡 Upload mobsfscan report
        if: always() && hashFiles('results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
